[colors.primary]
background = "#F1EFEB"  # bg -> grays["850"]
foreground = "#0E0E0E"  # norm -> grays["050"]

[colors.normal]
black   = "#1C1C1C"     # norm_subtle -> grays["100"]
red     = "#D2A7DC"     # delete -> purple_pastel
green   = "#6FB061"     # add -> green_pastel
yellow  = "#F9BA8A"     # change -> orange_pastel
blue    = "#994fb2"     # purple_light
magenta = "#733381"     # error -> purple_dark
cyan    = "#7BB662"     # hint -> green_light
white   = "#AAA9A6"     # grays["600"]

[colors.bright]
black   = "#2A2A29"     # norm_very_subtle -> grays["150"]
red     = "#F58024"     # warn -> orange_dark
green   = "#589C48"     # literal -> green_dark
yellow  = "#fbb149"     # visual -> orange_light
blue    = "#B8B7B4"     # grays["650"]
magenta = "#8E8D8A"     # grays["500"]
cyan    = "#636261"     # grays["350"]
white   = "#FFFDF9"     # oob -> grays["900"]

[colors.cursor]
cursor = "#0E0E0E"       # Same as foreground
text   = "#F1EFEB"       # Same as background

[colors.selection]
text       = "#0E0E0E"
background = "#E3E1DD"   # cursor_line -> grays["800"]
